services:
    _defaults:
        autowire: true
        bind:
            $root_path: '%core.root_path%'
            $php_ext: '%core.php_ext%'

    kaileymsnay.usertopics.listener:
        class: kaileymsnay\usertopics\event\main_listener
        tags:
            - { name: event.listener }
